# Generated by Django 5.0.1 on 2024-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_service_description_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, руб.'),
        ),
    ]
