# Generated by Django 5.0.1 on 2024-02-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
    ]
