# Generated by Django 5.0.1 on 2024-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='staff_images', verbose_name='Изображение'),
        ),
    ]
