# Generated by Django 5.0.1 on 2024-02-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_service_category_staff_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='category',
        ),
    ]
