# Generated by Django 5.0.1 on 2024-02-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job',
            field=models.CharField(blank=True, max_length=150, verbose_name='Специальность'),
        ),
    ]
