# Generated by Django 5.0.1 on 2024-02-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_staff_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='slug',
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория'),
        ),
    ]
