# Generated by Django 5.0.1 on 2024-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_staff_slug_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
    ]
